### PR TITLE
Pivot wider can handle numeric column in names_from

### LINKED ISSUE #214: pivot_wider(): wrong names when names from numeric column + names_prefix
Doesn't work correctly for a numeric column

``` r
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)
library(tidyr)

tibble(
  id = 1,
  name = 1:2,
  value = 11:12
) %>% 
  lazy_dt() %>% 
  pivot_wider(names_prefix = "col")
#> Source: local data table [1 x 3]
#> Call:   setnames(dcast(`_DT1`, formula = id ~ name, value.var = "value"), 
#>     old = 1:2, new = c("col1", "col2"))
#> 
#>    col1  col2   `2`
#>   <dbl> <int> <int>
#> 1     1    11    12
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

but works when cast to character before

``` r
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)
library(tidyr)

tibble(
  id = 1,
  name = as.character(1:2),
  value = 11:12
) %>% 
  lazy_dt() %>% 
  pivot_wider(names_prefix = "col")
#> Source: local data table [1 x 3]
#> Call:   setnames(dcast(`_DT1`, formula = id ~ name, value.var = "value"), 
#>     old = c("1", "2"), new = c("col1", "col2"))
#> 
#>      id  col1  col2
#>   <dbl> <int> <int>
#> 1     1    11    12
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### PR DESCRIPTION
**Pull request by mgirlich**
Fixes #214

### CODE REVIEW

File: R/step-call-pivot_wider.R [hunk 1]
```diff
@@ -75,6 +75,7 @@ pivot_wider.dtplyr_step <- function(data,
   } else {
     new_vars <- unique(pull(data, !!sym(names_from)))
   }
+  new_vars <- as.character(new_vars)
```
Comment (markfairbanks) [inline R/step-call-pivot_wider.R:78]: The new line can be moved inside the "else" condition - when `length(names_from) > 1` the `paste()` call will already have `new_vars` as character.

**Comment by hadley** [comment]
Can you add a news bullet please?
