### PR TITLE
Can pass quosure to `col` arg in `separate()`

### LINKED ISSUE #359: `separate()` fails when the input is a `data.table` instead of a `lazy_dt`
``` r
library(dtplyr)
library(tidyr, warn.conflicts = FALSE)
library(data.table, warn.conflicts = FALSE)

df <- data.table(x = c("a_a", "b_b", "c_c"))

df %>%
  separate(x, into = c("left", "right"))
#> Warning: Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
#> Please use `as_label()` or `as_name()` instead.
#> This warning is displayed once per session.
#> Warning in remove && !as.character(col) %in% into: 'length(x) = 2 > 1' in
#> coercion to 'logical(1)'
#> Error in ~x: object 'x' not found
```

### PR DESCRIPTION
**Pull request by markfairbanks**
Closes #359

### CODE REVIEW

**Review by eutwt — APPROVED** [review]
LGTM

File: R/step-subset-separate.R [hunk 1]
```diff
@@ -50,7 +50,7 @@ separate.dtplyr_step <- function(data, col, into,
     abort("`sep` must be a character vector.")
   }
 
-  col <- enexpr(col)
+  col <- quo_squash(enexpr(col))
```
Comment (eutwt) [inline R/step-subset-separate.R:53]: To allow for numeric arguments, and only those coercible to integer (e.g. not `1.5`), we could add after this

```R
if (is.numeric(col)) {                                                           
  col <- as.symbol(vctrs::vec_slice(data$vars, col))                             
} 
```

File: tests/testthat/test-step-subset-separate.R [hunk 2]
```diff
@@ -67,3 +67,14 @@ test_that("only copies when necessary", {
...
+test_that("can pass quosure to `col` arg, #359", {
+  dt <- lazy_dt(tibble(combined = c("a_b", "a_b")), "DT")
+  separate2 <- function(df, col, into) {
+    collect(separate(df, {{ col }}, into))
+  }
+  out <- separate2(dt, combined, into = c("a", "b"))
+  expect_named(out, c("a", "b"))
+  expect_equal(out$a, c("a", "a"))
+  expect_equal(out$b, c("b", "b"))
+})
```
Comment (eutwt) [inline tests/testthat/test-step-subset-separate.R:80]: Tests for numeric `col` arguments, if it's added to this PR

```R
test_that("can use numeric `col` arg", {
  dt <- lazy_dt(tibble(combined = c("a_b", "a_b")), "DT")

  out <- collect(separate(dt, 1, into = c("a", "b")))
  expect_named(out, c("a", "b"))
  expect_equal(out$a, c("a", "a"))
  expect_equal(out$b, c("b", "b"))

  expect_snapshot_error(separate(dt, 1.5,  into = c("a", "b")))
})
```

**Review by eutwt — APPROVED** [review]

**Comment by markfairbanks** [comment]
@eutwt I ended up using `tidyselect::eval_select()` to allow for numeric selection. I also added your recommended test, but I left out the snapshot since the error message is taken care of by `tidyselect`.

**Comment by eutwt** [comment]
@markfairbanks  I think it should error on >1 column

``` r
library(tidyr, warn.conflicts = FALSE)
library(data.table, warn.conflicts = FALSE)
devtools::load_all("/Users/mbp/Documents/GitHub/dtp")
#> ℹ Loading dtplyr
#> Warning: package 'dplyr' was built under R version 4.1.2

dt <- data.table(x = c("a_a", "b_b", "c_c"))[, y := x]
df <- as.data.frame(dt)

df %>% 
  separate(c(x, y), into = c("left", "right")) 
#> Error in `pull_as_location2()`:
#> ! Must extract column with a single valid subscript.
#> ✖ Subscript `var` has size 2 but must be size 1.
dt %>% 
  separate(c(x, y), into = c("left", "right")) 
#> Source: local data table [3 x 3]
#> Call:   copy(`_DT1`)[, `:=`(c("left", "right"), tstrsplit(x, split = "[^[:alnum:]]+"))][, 
#>     .(y, left, right)]
#> 
#>   y     left  right
#>   <chr> <chr> <chr>
#> 1 a_a   a     a    
#> 2 b_b   b     b    
#> 3 c_c   c     c    
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
