### PR TITLE
Join without merge

### LINKED ISSUE #198: join by named fields  causes an error
join using ``by=c(some_field_name="date")`` or ``by=c(some_field_name="dt")`` causes
an error when used inside a function.
the same works fine if called from top-level environment

<details>

```r
# fresh session
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)


a <- 
  tibble(
    s=sample(1:3,100,replace=TRUE),
    d1=1:100,
    testing123=1:100,
    dt=1:100,
    date=1:100,
    da=1:100,
    day=1:100,
    z=rnorm(length(s))
  ) %>%
  lazy_dt()

b <-
  tibble(
    s=sample(1:3,100,replace=TRUE),
    d1=1:100,
    testing123=1:100,
    dt=1:100,
    date=1:100,
    da=1:100,
    day=1:100,
    ed=cummax(seq_along(s)*(seq_along(s)%%10==1)),
    p=rnorm(length(s))
  ) %>%
  lazy_dt()

f<-function(a,b,what="d1")
{
  a %>%
    select(s) %>%
    distinct() %>%
    left_join(b,by="s") %>%
    left_join(
      select(a,s,(!!what),z),
      by=c("s",ed=what)
    ) %>%
    group_by(s,!!as.symbol(what)) %>%
    summarise(res=p*z) %>%
    ungroup() 
}

# dt, d1, date, da, day, testing123 all identical fields,
# the code should work for all
# but does not work for "dt" and "date"


# this works
# a,b inputs are lazy_dt
f(a,b,"testing123")

# this gives an error
# "date" and "dt" cause error
# when used inside function
f(a,b,"dt")

# this works
# so error only happens for lazy_dt() inputs
f(as_tibble(a),as_tibble(b),"dt")

# this works
# lazy_dt inputs are ok with "testing123"
# field name
f(lazy_dt(a),lazy_dt(b),"testing123")

# this does work
# and "d1" field name
f(a,b,"d1")

# this does not work
# but lazy_dt does not like "date"
# in joins
f(a,b,"date")

# but this does work
# at top-level environment "date"
# does not give an error.
# only inside function call
what<-"date"
a %>%
  select(s) %>%
  distinct() %>%
  left_join(b,by="s") %>%
  left_join(
    select(a,s,(!!what),z),
    by=c("s",ed=what)
  ) %>%
  group_by(s,!!as.symbol(what)) %>%
  summarise(res=p*z) %>%
  ungroup() 

```

image

</details>

### LINKED ISSUE #222: Issues when joining by named vector
I wanted to fix #198 and discovered some more issues when joining by a named vector:

* wrong `tbl_vars` for `left/full/inner_join()`
* wrong column order in `left/full/inner_join()`
* `right_join()` complains about missing variable
* `semi/anti_join()` complain about missing variable

``` r
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

df1 <- data.frame(x = 1, y = 1, z = 2)
df2 <- data.frame(x = 1, y = 2)
dt1 <- lazy_dt(df1, "dt1")
dt2 <- lazy_dt(df2, "dt2")

# left/full/inner
left_join(dt1, dt2, by = c("x", z = "y"))
#> Source: local data table [1 x 3]
#> Call:   merge(dt1, dt2, all.x = TRUE, all.y = FALSE, by.x = c("x", "z"
#> ), by.y = c("x", "y"), allow.cartesian = TRUE)
#> 
#>       x     z     y
#>   <dbl> <dbl> <dbl>
#> 1     1     2     1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
left_join(df1, df2, by = c("x", z = "y"))
#>   x y z
#> 1 1 1 2

# note the wrong order here
left_join(dt1, dt2, by = c("x", z = "y")) %>% tbl_vars()
#> <dplyr:::vars>
#> [1] "x"   "z"   "y.x" "y.y"

# right
right_join(dt1, dt2, by = c("x", z = "y"))
#> Error: `by` can't contain join column `z` which is missing from LHS.
right_join(df1, df2, by = c("x", z = "y"))
#>   x y z
#> 1 1 1 2

# semi/anti
semi_join(dt1, dt2, by = c("x", z = "y"))
#> Error: argument specifying columns specify non existing column(s): cols[2]='z'
semi_join(df1, df2, by = c("x", z = "y"))
#>   x y z
#> 1 1 1 2

anti_join(dt1, dt2, by = c("x", z = "y"))
#> Error in colnamesInt(i, unname(on), check_dups = FALSE): argument specifying columns specify non existing column(s): cols[2]='z'
anti_join(df1, df2, by = c("x", z = "y"))
#> [1] x y z
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### LINKED ISSUE #243: `select()` after `right_join()` removes `allow.cartesian = TRUE`
``` r
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)

x <- right_join(
  band_members %>% lazy_dt(),
  band_instruments %>% lazy_dt(),
  by = "name"
)

x %>% show_query()
#> `_DT1`[`_DT2`, on = .(name), allow.cartesian = TRUE]
x %>% select(name) %>% show_query()
#> `_DT1`[`_DT2`, .(name), on = .(name)]
```

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by mgirlich**
The main goal was to ensure correct handling of a named `by` in the joins and to ensure correct column names also in edge cases. Now, `left/right/inner_join()` always use `[.data.table()`. Unfortunately, this makes the translation of `left_join()` longer as it now usually requires calls to both, `setcolorder()` and `setnames()`.

Could make use of `step_setnames()` added in PR #241.

Relates to #239. Fixes #243 and fixes #222 and fixes #198.

### CODE REVIEW

File: R/step-colorder.R [hunk 1]
```diff
@@ -1,11 +1,23 @@
-step_colorder <- function(parent, col_order) {
-  stopifnot(is_step(parent))
-  stopifnot(is.character(col_order))
+step_colorder <- function(x, col_order) {
+  stopifnot(is_step(x))
+  stopifnot(is.character(col_order) || is.integer(col_order))
 
-  step_call(parent,
+  if (is.integer(col_order)) {
+    if (all(col_order == seq_along(col_order))) {
```
Comment (hadley) [inline R/step-colorder.R:6]: I think that should use `identical()` since `==` is vectorised?

Comment (hadley) [reply R/step-colorder.R:6]: And maybe move the check until after handling the different types? i.e. `if (identical(vars, x$vars)) ...`

File: R/step-join.R [hunk 2]
```diff
@@ -210,25 +186,108 @@ dtplyr_auto_copy <- function(x, y, copy = copy) {
...
+    subset_join_vars(x, y, on_y)
+  } else if (style == "full") {
+    merge_vars(x, y, on_x, on_y, suffix)
+  } else {
+    x
+  }
+}
+
+#' column names as generated in `x[y, on = on]`
+#' @noRd
```
Comment (hadley) [inline R/step-join.R:210]:
```suggestion
# column names as generated in `x[y, on = on]`
```

File: R/step-join.R [hunk 3]
```diff
@@ -210,25 +186,108 @@ dtplyr_auto_copy <- function(x, y, copy = copy) {
...
+    }
+    x[[i]] <- nm
   }
+  x
+}
 
-  common_vars <- setdiff(intersect(x, y), by)
-  length(common_vars) == 0
+#' column names as generated by `merge(x, y, by.x = on_x, by.y = on_y)`
+#' @noRd
```
Comment (hadley) [inline R/step-join.R:238]:
```suggestion
# column names as generated by `merge(x, y, by.x = on_x, by.y = on_y)`
```

File: NEWS.md [hunk 4]
```diff
@@ -1,5 +1,10 @@
 # dtplyr (development version)
 
+* `left_join()`, `right_join()`, and `inner_join()` are now always translated to
```
Comment (hadley) [inline NEWS.md:3]: Comment on why this is a good thing?

File: R/step-join.R [hunk 5]
```diff
@@ -1,26 +1,42 @@
...
     style = style,
     locals = utils::modifyList(x$locals, y$locals),
     class = "dtplyr_step_join"
   )
+
+  if (style %in% c("anti", "semi")) {
+    return(out)
+  }
+
+  out <- step_colorder(out, colorder)
```
[the remark this answers is not in the document]
Comment (mgirlich) [reply R/step-join.R:29]: * `data.table::merge()` produces the order `join-vars, x-vars, y-vars`. `full_join()` produces the order `x-vars, y-vars`
* The left join in data.table is `y[x]` (instead of `x[y]`), so the order is `y-vars, x-vars` instead of `x-vars, y-vars` as in `left_join()`

File: R/step-join.R [hunk 6]
```diff
@@ -1,26 +1,42 @@
...
+
+  x_sim <- simulate_vars(x)
+  y_sim <- simulate_vars(y)
+  vars <- colnames(left_join(x_sim, y_sim, by = stats::setNames(on$y, on$x)))
```
[the remark this answers is not in the document]
Comment (mgirlich) [reply R/step-join.R]: This actually helped me realize that suffixes weren't used at all 👍

File: NEWS.md (hunk 4 above)
Comment (mgirlich) [reply NEWS.md:3]: I'm not sure there are direct advantages for the user. My main motivation was to fix handling of joining by differently named columns and handling of duplicate column names. Code wise I think it is a bit nicer that it isn't necessary anymore to distinguish between "simple" and "non-simple" joins.

Comment (hadley) [reply NEWS.md:3]: Ok, makes sense.

Comment (hadley) [reply NEWS.md:3]: Could you please include a bit of this justification in the news bullet? i.e. it makes the translation a bit longer for simple merges, but the advantage is that ...

**Review by hadley — APPROVED** [review]

File: R/step-join.R [hunk 7]
```diff
@@ -33,38 +49,32 @@ dt_sources.dtplyr_step_join <- function(x) {
...
-  if (is_call(call, "merge") && !identical(x$suffix, c(".x", ".y"))) {
-    call$suffixes <- x$suffix
-  }
+  on <- call2(".", !!!syms(on2))
 
-  call
+  switch(x$style,
+    full = call2("merge", lhs, rhs, all = TRUE, by.x = x$on$x, by.y = x$on$y, allow.cartesian = TRUE),
+    left = call2("[", lhs, rhs, on = on, allow.cartesian = TRUE),
+    inner = call2("[", lhs, rhs, on = on, nomatch = NULL),
```
[the remark this answers is not in the document]
Comment (mgirlich) [reply R/step-join.R:59]: I'm pretty sure this was by accident.
